#加密配置
jasypt:
  encryptor:
    password: summer

server:
  port: ${random.int[10000,19999]}
  tomcat:
    max-threads: 500 # Maximum amount of worker threads.
    min-spare-threads: 50 # Minimum amount of worker threads
zuul:
  add-host-header: true
#  ignored-services:
  retryable: true #是否开启重试功能
  ribbon:
    eager-load:
      enabled: true
  routes:
    config-servers:
        path: /swagger-servers/**
        serviceId: cloud-swagger-doc
        sensitive-headers: Cookie,Set-Cookie
#    manages:
#      path: /manage/**
#      serviceId: cloud-manage-server
#      sensitive-headers: Cookie,Set-Cookie
#    invokes:
#      path: /invoke/**
#      serviceId: cloud-invoke-server
#      sensitive-headers: Cookie,Set-Cookie
#    users:
#      path: /users/**
#      serviceId: cloud-users-server
#      sensitive-headers: Cookie,Set-Cookie
#    tasks:
#      path: /scheduled-task/**
#      serviceId: cloud-scheduled-task-server
#      sensitive-headers: Cookie,Set-Cookie
#    risks:
#      path: /risk-warning/**
#      serviceId: cloud-risk-warning-server
#      sensitive-headers: Cookie,Set-Cookie
spring:
  redis:
    remote: false        #cachecloud 获取
    host: localhost
    port: 6379
    password:
  http:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

cache:
  redis:
    expiration: 3601

ribbon:
  Httpclient:
    enable: false
  OkHttp:
    enable: true
  MaxAutoRetries: 3 #同一个Server重试的次数(除去首次)
  MaxAutoRetriesNextServer: 0 #切换相同Server的次数
  ReadTimeout: 30000
  ConnectTimeout: 30000
  eager-load:
        enabled: true

feign:
  hystrix:
    enabled: true
  okhttp:
    enable: true
  httpclient:
    enable: false
  client:
    config:
      feignName:
        connectTimeout: 30000
        readTimeout: 30000

hystrix:
  threadpool:
    default:
      coreSize: 500
      maxQueueSize: 1000
      queueSizeRejectionThreshold: 800
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

#监控短点配置
management:
  security:
    enabled: false
security:
  user:
    name: user
    password: user
  basic:
    enabled: false
endpoints:
  actuator:
    enabled: true
  shutdown:
    enabled: false

logging:
  config: classpath:logback.xml