server:
  port: 7000
  servlet-path: /
security:
  user:
    name: user
    password: user
  basic:
    enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:user@eureka-server:8761/eureka/   # 指定注册中心的地址
  instance:
    preferIpAddress: true
#    hostname : discovery   # 指定主机名时候通过主机名访问,否则通过ip地址
spring:
  application:
    name: monitor-user-service    # 项目名称尽量用小写
spring:
  datasource:
    url: jdbc:mysql://eureka-server:3306/user-server-db?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.monitor.model
  configLocation: classpath:mybatis/mybatis-config.xml

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql