server:
  port: 1000         # 指定该zuul实例的端口
security:
  user:
    name: user
    password: user
spring:
  application:
    name: cloud-gateway-zuul    # 项目名称尽量用小写
zuul:
  add-host-header: true
  routes:
    config-servers:
        path: /config-servers/**
        serviceId: cloud-config-server
        sensitive-headers: Cookie,Set-Cookie
    manages:
      path: /manage/**
      serviceId: cloud-manage-server
      sensitive-headers: Cookie,Set-Cookie
    invokes:
      path: /invoke/**
      serviceId: cloud-invoke-server
      sensitive-headers: Cookie,Set-Cookie
    users:
      path: /users/**
      serviceId: cloud-users-server
      sensitive-headers: Cookie,Set-Cookie
    tasks:
      path: /scheduled-task/**
      serviceId: cloud-scheduled-task-server
      sensitive-headers: Cookie,Set-Cookie
    risks:
      path: /risk-warning/**
      serviceId: cloud-risk-warning-server
      sensitive-headers: Cookie,Set-Cookie
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:user@eureka-server:8761/eureka/,http://user:user@eureka-server:8762/eureka/   # 指定注册中心的地址
  instance:
    preferIpAddress: true
#    hostname : discovery   # 指定主机名时候通过主机名访问,否则通过ip地址
logging:
  config: classpath:logback.xml