server:
  port: 4001

spring:
  application:
    name: cloud-config-server
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xie-summer/new-cloud-config.git
---
spring:
  profiles: dev
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    serviceUrl:
      defaultZone: http://user:user@eureka-server:1025/eureka

---
spring:
  profiles: prd
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://user:user@eureka-server:1025/eureka
